export const degrees = [
  { title: "Bachelor of Arts (B.A.)", value: "Bachelor of Arts (B.A.)" },
  { title: "Bachelor of Science (B.S.)", value: "Bachelor of Science (B.S.)" },
  { title: "Bachelor of Fine Arts (BFA)", value: "Bachelor of Fine Arts (BFA)" },
  { title: "Bachelor of Business Administration (BBA)", value: "Bachelor of Business Administration (BBA)" },
  { title: "Bachelor of Engineering (B.Eng.)", value: "Bachelor of Engineering (B.Eng.)" },
  { title: "Bachelor of Education (B.Ed.)", value: "Bachelor of Education (B.Ed.)" },
  { title: "Bachelor of Technology (B.Tech)", value: "Bachelor of Technology (B.Tech)" },
  { title: "Bachelor of Medicine, Bachelor of Surgery (MBBS)", value: "Bachelor of Medicine, Bachelor of Surgery (MBBS)" },
  { title: "Master of Arts (M.A.)", value: "Master of Arts (M.A.)" },
  { title: "Master of Science (M.S.)", value: "Master of Science (M.S.)" },
  { title: "Master of Business Administration (MBA)", value: "Master of Business Administration (MBA)" },
  { title: "Master of Fine Arts (MFA)", value: "Master of Fine Arts (MFA)" },
  { title: "Master of Education (M.Ed.)", value: "Master of Education (M.Ed.)" },
  { title: "Master of Engineering (M.Eng.)", value: "Master of Engineering (M.Eng.)" },
  { title: "Master of Public Health (MPH)", value: "Master of Public Health (MPH)" },
  { title: "Master of Social Work (MSW)", value: "Master of Social Work (MSW)" },
  { title: "Master of Laws (LL.M.)", value: "Master of Laws (LL.M.)" },
  { title: "Doctor of Philosophy (Ph.D.)", value: "Doctor of Philosophy (Ph.D.)" },
  { title: "Doctor of Medicine (M.D.)", value: "Doctor of Medicine (M.D.)" },
  { title: "Doctor of Education (Ed.D.)", value: "Doctor of Education (Ed.D.)" },
  { title: "Doctor of Psychology (Psy.D.)", value: "Doctor of Psychology (Psy.D.)" },
  { title: "Doctor of Business Administration (DBA)", value: "Doctor of Business Administration (DBA)" },
  { title: "Doctor of Nursing Practice (DNP)", value: "Doctor of Nursing Practice (DNP)" },
  { title: "Doctor of Jurisprudence (J.D.)", value: "Doctor of Jurisprudence (J.D.)" },
  { title: "Juris Doctor (J.D.) - Law", value: "Juris Doctor (J.D.) - Law" },
  { title: "Doctor of Pharmacy (Pharm.D.)", value: "Doctor of Pharmacy (Pharm.D.)" },
  { title: "Doctor of Veterinary Medicine (DVM)", value: "Doctor of Veterinary Medicine (DVM)" },
  { title: "Associate of Arts (A.A.)", value: "Associate of Arts (A.A.)" },
  { title: "Associate of Science (A.S.)", value: "Associate of Science (A.S.)" },
  { title: "Associate of Applied Science (AAS)", value: "Associate of Applied Science (AAS)" },
  { title: "Associate of Engineering (AE)", value: "Associate of Engineering (AE)" },
  { title: "Associate of Business Administration (ABA)", value: "Associate of Business Administration (ABA)" },
  { title: "Postgraduate Diploma", value: "Postgraduate Diploma" },
  { title: "Graduate Certificate", value: "Graduate Certificate" },
  { title: "Professional Certificate", value: "Professional Certificate" },
  { title: "Vocational Diploma", value: "Vocational Diploma" },
  { title: "High School Diploma (Secondary Education)", value: "High School Diploma (Secondary Education)" },
];
