name: Firstpipline

on:
  workflow_dispatch:

jobs:
  Staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 156.67.80.49
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/hadielearn-prod-13
            git pull
            npm install -f
            pm2 reload api --update-env

